local colors = {
	-- PATCH_OPEN
	Normal = { fg = "#DFDCE4", bg = "#221B32" },
	typescriptGlobal = { link = "Normal" },
	typescriptObjectType = { link = "Normal" },
	typescriptPredefinedType = { link = "Normal" },
	Boolean = { fg = "#EF15C0" },
	BufferLineBackground = {},
	BufferLineBuffer = { link = "BufferLineBackground" },
	BufferLineBufferSelected = { bold = true, italic = true },
	BufferLineFill = { bg = "#120D0E" },
	BufferLineTabClose = { link = "BufferLineFill" },
	BufferLineModified = { bg = "#00CC8F" },
	BufferLineModifiedSelected = { link = "BufferLineModified" },
	BufferLineModifiedVisible = { link = "BufferLineModified" },
	BufferLineTab = { fg = "#FFFFFF", bg = "#f00000" },
	Builtin = { fg = "#DFDCE4" },
	CMYKBackstick = { link = "CMYKQuote" },
	Character = { fg = "#B596F8" },
	Comment = { fg = "#807693", italic = true },
	jsonCommentError = { link = "Comment" },
	Conditional = { fg = "#EF15C0" },
	Constant = { fg = "#DFDCE4" },
	Constructor = { fg = "#15AEEF" },
	Cursor = { fg = "#221B32", bg = "#DFDCE4" },
	CursorLine = { bg = "#2B223F" },
	CursorColumn = { link = "CursorLine" },
	CursorLineNr = { fg = "#EF15C0", bg = "#120D0E" },
	DiagnosticError = { fg = "#EF15C0", bg = "#120D0E" },
	DiagnosticHint = { fg = "#15AEEF", bg = "#120D0E" },
	DiagnosticInfo = { fg = "#00CC8F", bg = "#120D0E" },
	DiagnosticVirtualTextError = { fg = "#EF15C0", bg = "#463767", bold = true },
	DiagnosticVirtualTextHint = { fg = "#15AEEF", bg = "#463767" },
	DiagnosticVirtualTextInfo = { fg = "#00CC8F", bg = "#463767" },
	DiagnosticVirtualTextWarn = { fg = "#EF9815", bg = "#463767" },
	DiagnosticWarn = { fg = "#EF9815", bg = "#120D0E" },
	DiffAdd = { bg = "#15EFAE" },
	GitGutterAdd = { link = "DiffAdd" },
	DiffChange = { bg = "#EF9815" },
	GitGutterChange = { link = "DiffChange" },
	DiffDelete = { bg = "#EF1561" },
	GitGutterDelete = { link = "DiffDelete" },
	DiffText = { bg = "#EF9815" },
	Directory = { fg = "#B596F8" },
	EndOfBuffer = { fg = "#221B32" },
	Error = { fg = "#f00000" },
	Exception = { fg = "#EF15C0" },
	Field = { fg = "#DFDCE4" },
	Float = { fg = "#EF9815" },
	Function = { fg = "#15EFAE" },
	typescriptFuncCall = { link = "Function" },
	typescriptIdentifierName = { link = "Function" },
	typescriptMember = { link = "Function" },
	Identifier = { fg = "#EF15C0" },
	typescriptImport = { link = "Identifier" },
	IncSearch = { fg = "#DFDCE4", bg = "#463767", bold = true },
	Include = { fg = "#EF15C0" },
	Keyword = { fg = "#15AEEF" },
	typescriptAliasDeclaration = { link = "Keyword" },
	typescriptClassName = { link = "Keyword" },
	typescriptEnum = { link = "Keyword" },
	typescriptEnumKeyword = { link = "Keyword" },
	typescriptInterfaceName = { link = "Keyword" },
	typescriptTypeReference = { link = "Keyword" },
	typescriptVariable = { link = "Keyword" },
	KeywordOperator = { fg = "#B596F8" },
	KeywordReturn = { fg = "#EF15C0" },
	LineNr = { fg = "#DFDCE4", bg = "#120D0E" },
	Macro = { fg = "#EF15C0" },
	MatchParen = { fg = "#D4D1DC", bg = "#463767" },
	Menu = { fg = "#DFDCE4", bg = "#221B32" },
	Method = { fg = "#15EFAE" },
	ModeMsg = { fg = "#DFDCE4", bg = "#221B32" },
	NormalNC = { fg = "#9B92AB", bg = "#191424" },
	Number = { fg = "#EF9815" },
	Operator = { fg = "#B596F8" },
	Pmenu = { fg = "#DFDCE4", bg = "#392D53" },
	PmenuSBar = { bg = "#463767" },
	PmenuSel = { fg = "#EF15C0", bg = "#302546" },
	PmenuThumb = { bg = "#302546" },
	Prepoc = { fg = "#EF15C0" },
	Repeat = { fg = "#EF15C0" },
	Search = { fg = "#DFDCE4", bg = "#463767", bold = true },
	SignColumn = { bg = "#120D0E" },
	SignColumnSB = { bg = "#120D0E" },
	Statement = { fg = "#EF15C0" },
	String = { fg = "#B596F8" },
	jsonString = { link = "String" },
	typescriptString = { link = "String" },
	typescriptTemplate = { link = "String" },
	StringRegex = { fg = "#EF15C0" },
	TSAttribute = { fg = "#EBEF15" },
	TSCharacter = { fg = "#B596F8" },
	TSComment = { fg = "#807693" },
	TSConditional = { fg = "#EF15C0" },
	TSConstBuiltin = { fg = "#EF15C0" },
	TSConstMacro = { fg = "#EF15C0" },
	TSConstant = { fg = "#DFDCE4" },
	TSConstructor = { fg = "#15AEEF" },
	TSEmphasis = { fg = "#DFDCE4", italic = true },
	TSError = { fg = "#f00000" },
	TSException = { fg = "#EF15C0" },
	TSField = { fg = "#DFDCE4" },
	TSFloat = { fg = "#EF9815" },
	TSFuncBuiltin = { fg = "#DFDCE4" },
	TSFuncMacro = { fg = "#15EFAE" },
	TSFunction = { fg = "#15EFAE" },
	TSInclude = { fg = "#EF15C0" },
	TSKeyword = { fg = "#15AEEF" },
	TSKeywordFunction = { fg = "#15AEEF" },
	TSKeywordOperator = { fg = "#B596F8" },
	TSKeywordReturn = { fg = "#EF15C0" },
	TSLabel = { fg = "#7415EF" },
	TSLiteral = { fg = "#DFDCE4" },
	TSMethod = { fg = "#15EFAE" },
	TSNamespace = { fg = "#EF15C0" },
	TSNumber = { fg = "#EF9815" },
	TSOperator = { fg = "#B596F8" },
	TSParameter = {},
	TSParameterReference = {},
	TSProperty = { fg = "#DFDCE4" },
	TSPunctBracket = { fg = "#EBEF15" },
	CMYKQuote = { link = "TSPunctBracket" },
	TSPunctDelimiter = { fg = "#EBEF15" },
	TSPunctSpecial = { fg = "#EBEF15" },
	TSRepeat = { fg = "#EF15C0" },
	TSStatement = { fg = "#f00000" },
	TSString = { fg = "#B596F8" },
	TSStringEscape = { fg = "#EF15C0" },
	TSStringRegex = { fg = "#EF15C0" },
	TSStrong = { fg = "#DFDCE4", bold = true },
	TSTag = { fg = "#EF15C0" },
	TSTagDelimiter = { fg = "#EBEF15" },
	TSText = { fg = "#DFDCE4" },
	TSTextReference = { fg = "#DFDCE4" },
	TSTitle = {},
	TSType = { fg = "#15AEEF" },
	TSTypeBuiltin = { fg = "#DFDCE4" },
	TSURI = { fg = "#DFDCE4", underline = true },
	TSVariable = { fg = "#DFDCE4" },
	TSVariableBuiltin = { fg = "#DFDCE4" },
	TabLine = { fg = "#DFDCE4", bg = "#120D0E" },
	TabLineFill = { fg = "#DFDCE4", bg = "#120D0E" },
	TabLineSell = { fg = "#DFDCE4", bg = "#120D0E", bold = true, italic = true },
	Title = {},
	Todo = { fg = "#DFDCE4", bg = "#EF15C0", bold = true },
	TSTodo = { link = "Todo" },
	Type = { fg = "#15AEEF" },
	TypeBuiltin = { fg = "#DFDCE4" },
	Variable = { fg = "#DFDCE4" },
	typescriptVariableDeclaration = { link = "Variable" },
	Visual = { bg = "#878192" },
	Warn = { fg = "#EF9815" },
	jsonFold = { fg = "#EF15C0" },
	jsonKeyword = { fg = "#15EFAE" },
	jsonKeywordMatch = { fg = "#EBEF15" },
	jsonNoise = { fg = "#EBEF15" },
	jsonQuote = { fg = "#EBEF15" },
	markdownBold = { fg = "#DFDCE4", bold = true },
	markdownCode = { fg = "#DFDCE4" },
	markdownCodeDelimiter = { fg = "#DFDCE4" },
	markdownEscape = { fg = "#DFDCE4" },
	markdownFootnote = { fg = "#DFDCE4" },
	markdownFootnoteDefinition = { fg = "#DFDCE4" },
	markdownHeadingDelimiter = { fg = "#DFDCE4" },
	markdownLinkText = { fg = "#DFDCE4" },
	markdownRule = { fg = "#DFDCE4", bold = true },
	markdownTSLiteral = { fg = "#DFDCE4" },
	markdownUrl = { fg = "#DFDCE4", underline = true },
	markdown_inlineTSLiteral = { fg = "#DFDCE4" },
	typescriptBinaryOp = { fg = "#B596F8" },
	typescriptBraces = { fg = "#EBEF15" },
	typescriptEndColons = { link = "typescriptBraces" },
	typescriptParens = { link = "typescriptBraces" },
	typescriptCall = { fg = "#DFDCE4" },
	typescriptConstructor = { fg = "#15EFAE" },
	typescriptDecorator = { fg = "#15EFAE" },
	typescriptExceptions = { fg = "#EF15C0" },
	typescriptForOperator = { fg = "#B596F8" },
	typescriptFuncComma = { fg = "#EBEF15" },
	typescriptIdentifier = { fg = "#EF15C0" },
	typescriptObjectLabel = { fg = "#DFDCE4" },
	typescriptOperator = { fg = "#B596F8" },
	typescriptProp = { fg = "#EF15C0" },
	typescriptRegexpString = { fg = "#EF15C0" },
	typescriptSpecial = { fg = "#EF15C0" },
	typescriptTernaryOp = { fg = "#B596F8" },
	typescriptTry = { fg = "#EF15C0" },
	-- PATCH_CLOSE
}

vim.cmd([[highlight clear]])
vim.opt.termguicolors = true
vim.g.colors_name = "cmyk-colourrr"

for group, attrs in pairs(colors) do
	vim.api.nvim_set_hl(0, group, attrs)
end
